### ISSUE TITLE
acura_ilx_2016_can_generated.dbc does not open with CANdb++

### ISSUE THREAD

**Issue by rusefillc** [commaai/opendbc#660] opened 2022-07-06 14:41 UTC
is that a feature or a bug?

![image](https://user-images.githubusercontent.com/48498823/177577213-be58154f-9729-45f5-9abc-ec018617ef8d.png)

![image](https://user-images.githubusercontent.com/48498823/177577251-f81a2c2e-e474-433f-b7d2-dfaf81540931.png)

**Comment by adeebshihadeh** [comment] 2022-07-06 17:14
Duplicate of #151

**Closed by adeebshihadeh** 2022-07-06 17:14 UTC
